name: main

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: 20
      - run: yarn install --frozen-lockfile

      - run: npm run type
      # - run: npm run lint
      - run: npm run test --ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: update action.yml to use image from local Dockerfile
        run: |
          sed -i "s/image: .*/image: Dockerfile/" action.yml

      - name: generate-snake-game-from-github-contribution-grid
        id: generate-snake
        uses: ./
        with:
          github_user_name: platane
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/github-contribution-grid-snake.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
            dist/github-contribution-grid-without-stack.gif?hide_stack=true

      - name: ensure the generated file exists
        run: |
          ls dist
          test -f dist/github-contribution-grid-snake.svg
          test -f dist/github-contribution-grid-snake-dark.svg
          test -f dist/github-contribution-grid-snake.gif
          test -f dist/github-contribution-grid-without-stack.gif

      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test-action-svg-only:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: 20
      - run: yarn install --frozen-lockfile

      - name: build svg-only action
        run: |
          npm run build:action
          rm -r svg-only/dist
          mv packages/action/dist svg-only/dist

      - name: generate-snake-game-from-github-contribution-grid
        id: generate-snake
        uses: ./svg-only
        with:
          github_user_name: arthurlobopro
          outputs: |
            dist/grid-snake.svg
            dist/grid-snake-dark.svg?palette=github-dark
            dist/grid-without-progressbar.svg?hide_stack=true
            dist/grid-snake-long.svg?snake_size=5

      - name: ensure the generated file exists
        run: |
          ls dist
          test -f dist/grid-snake.svg
          test -f dist/grid-snake-dark.svg
          test -f dist/grid-without-progressbar.svg
          test -f dist/grid-snake-long.svg

      - name: Generate Snake Sizes
        uses: ./svg-only
        with:
          github_user_name: arthurlobopro
          outputs: |
            dist/size/grid-snake-very-long.svg?snake_size=7
            dist/size/grid-snake-very-long-dark.svg?snake_size=7&palette=github-dark
            dist/size/grid-snake-short.svg?snake_size=2
            dist/size/grid-snake-short-dark.svg?snake_size=2&palette=github-dark
            dist/size/grid-snake-long.svg?snake_size=6
            dist/size/grid-snake-long-dark.svg?snake_size=6&palette=github-dark

      - name: Ensure Size Outputs Exists
        run: |
          ls dist/size
          test -f dist/size/grid-snake-short.svg
          test -f dist/size/grid-snake-short-dark.svg
          test -f dist/size/grid-snake-long.svg
          test -f dist/size/grid-snake-long-dark.svg
          test -f dist/size/grid-snake-very-long.svg
          test -f dist/size/grid-snake-very-long-dark.svg

      - name: Generate Speed Custom
        uses: ./svg-only
        with:
          github_user_name: arthurlobopro
          outputs: |
            dist/speed/grid-snake-slow.svg?speed=slow
            dist/speed/grid-snake-normal.svg?speed=normal
            dist/speed/grid-snake-fast.svg?speed=fast
            dist/speed/grid-snake-slow-dark.svg?speed=slow&palette=github-dark
            dist/speed/grid-snake-normal-dark.svg?speed=normal&palette=github-dark
            dist/speed/grid-snake-fast-dark.svg?speed=fast&palette=github-dark

      - name: Ensure Speed Outputs Exists
        run: |
          ls dist/speed
          test -f dist/speed/grid-snake-slow.svg
          test -f dist/speed/grid-snake-normal.svg
          test -f dist/speed/grid-snake-fast.svg
          test -f dist/speed/grid-snake-slow-dark.svg
          test -f dist/speed/grid-snake-normal-dark.svg
          test -f dist/speed/grid-snake-fast-dark.svg

      - name: Generate Dot Shape Custom
        uses: ./svg-only
        with:
          github_user_name: arthurlobopro
          outputs: |
            dist/shape/grid-snake-square.svg?dot_shape=square
            dist/shape/grid-snake-rounded-square.svg?dot_shape=rounded-square
            dist/shape/grid-snake-circle.svg?dot_shape=circle
            dist/shape/grid-snake-square-dark.svg?dot_shape=square&palette=github-dark
            dist/shape/grid-snake-rounded-square-dark.svg?dot_shape=rounded-square&palette=github-dark
            dist/shape/grid-snake-circle-dark.svg?dot_shape=circle&palette=github-dark

      - name: Ensure Speed Outputs Exists
        run: |
          ls dist/shape
          test -f dist/shape/grid-snake-square.svg
          test -f dist/shape/grid-snake-rounded-square.svg
          test -f dist/shape/grid-snake-circle.svg
          test -f dist/shape/grid-snake-square-dark.svg
          test -f dist/shape/grid-snake-rounded-square-dark.svg
          test -f dist/shape/grid-snake-circle-dark.svg

      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output-svg-only
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # deploy-ghpages:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-node@v3
  #       with:
  #         cache: yarn
  #         node-version: 20
  #     - run: yarn install --frozen-lockfile

  #     - run: npm run build:demo
  #       env:
  #         GITHUB_USER_CONTRIBUTION_API_ENDPOINT: https://snk-one.vercel.app/api/github-user-contribution/

  #     - uses: crazy-max/ghaction-github-pages@v3.1.0
  #       if: success() && github.ref == 'refs/heads/main'
  #       with:
  #         target_branch: gh-pages
  #         build_dir: packages/demo/dist
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN_GH_PAGES }}
